frozen = [ "Av", "global_cov", "global_cov:log_amp", "global_cov:log_ls",]

[parameters]
Av = 0
param1 = 1.6191830497111993e-9
param2 = 8.707624641896514
param3 = 1.9823314702995158

[metadata]
name = "SpectrumModel"
data = "Spectrum"
emulator = "Grid-Emulator_Files/SSpec_emu_60inc_850-1850A_10comp_123"

[parameters.global_cov]
log_amp = -56.0
log_ls = 5.0
