frozen = [ "Av",]

[parameters]
Av = 0
param1 = 1.5e-10
param2 = 4.0
param5 = 30000000000.0

[metadata]
name = "SpectrumModel"
data = "Spectrum"
emulator = "Grid-Emulator_Files/Emulator_full"

[parameters.global_cov]
log_amp = -52.0
log_ls = 5.0
